replicaCount: 1

image:
  repository: nexus-repo.zapto.org/repository/docker-repo/front
  tag: "v1.0.0"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  ingressClassName: nginx
  enabled: true
  annotations: {}
  hosts:
    - host: nginx.example.com
      paths:
        - path: /
          pathType: Prefix
